name: Reset
on:
  workflow_dispatch:

jobs:
  checks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: 'month'
            command: '-d "last month" +%B_%C%y'
          - name: 'year'
            command: '-d "last year" +%C%y'
    outputs:
      month: ${{ steps.get_date.outputs.month }}
      year: ${{ steps.get_date.outputs.year }}
      reset_month: ${{ steps.check_data.outputs.reset_month }}
      reset_year: ${{ steps.check_data.outputs.reset_year }}
    steps:
      - id: get_date
        run: echo "${{ matrix.name }}=$(date ${{ matrix.command }})" >> $GITHUB_OUTPUT
      - id: fetch_data
        uses: skgandikota/FetchUrl@v1.3
        with:
          url: "https://isbo-coddit-default-rtdb.firebaseio.com/${{ steps.get_date.outputs[matrix.name] }}.json"
      - id: check_data
        run: echo "reset_${{ matrix.name }}=${{ (fromJSON(steps.fetch_data.outputs.headers)).content-length[0] }}" >> $GITHUB_OUTPUT

  reset:
    needs: checks
    if: (needs.checks.outputs.reset_month == 4) || (needs.checks.outputs.reset_year == 4)
    runs-on: ubuntu-latest
    env:
      project_id: ${{ secrets.firebase_project_id }}
      private_key_id: ${{ secrets.firebase_private_key_id }}
      private_key: ${{ secrets.firebase_private_key }}
      client_email: ${{ secrets.firebase_client_email }}
      client_id: ${{ secrets.firebase_client_id }}
      client_x509_cert_url: ${{ secrets.firebase_client_x509_cert_url }}
      month: ${{ needs.checks.outputs.month }}
      year: ${{ needs.checks.outputs.year }}
      reset_month: ${{ needs.checks.outputs.reset_month }}
      reset_year: ${{ needs.checks.outputs.reset_year }}
    steps:
      - uses: actions/checkout@v2.7.0
      - uses: actions/setup-python@v3.1.3
      - run: |
          pip install actions-toolkit
          pip install firebase-admin
      - run: python .github/scripts/reset.py