name: Reset
on:
 schedule:
   - cron: '4 6 1 2-12 *'
   - cron: '4 6 1 1 *'
 workflow_dispatch:

jobs:
  checks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: 'month'
            command: '+%B%C%y'
            time: ''
          - name: 'year'
            command: '+%C%y'
            time: '4 6 1 1 *'
    outputs:
      month: ${{ steps.check.outputs.month }}
      year: ${{ steps.check.outputs.year }}
    steps:
      - id: current
        run: echo "date=$(date ${{ matrix.command }})" >> $GITHUB_OUTPUT
      - id: fetch
        uses: skgandikota/FetchUrl@v1.3
        with:
          url: "https://isbo-coddit-default-rtdb.firebaseio.com/${{ steps.current.outputs.date }}.json"
      - id: check
        run: |
          if [ '${{ github.event_name }}' == 'workflow_dispatch' ] || [ '' == '${{ matrix.time }}' ] || [ '${{ github.event.schedule }}' == '${{ matrix.time }}' ]; then
            echo "${{ matrix.name }}=${{ (fromJSON(steps.fetch.outputs.headers)).content-length[0] }}" >> $GITHUB_OUTPUT
          else
            echo "${{ matrix.name }}=0" >> $GITHUB_OUTPUT
          fi

  reset:
    needs: checks
    if: (needs.checks.outputs.month == 4) || (needs.checks.outputs.year == 4)
    runs-on: ubuntu-latest
    
    steps:
      - id: monthly
        if: (needs.checks.outputs.month == 4)
        run: echo "monthly"
      - id: yearly
        if: (needs.checks.outputs.year == 4)
        run: echo "yearly"
